###
# 게시판 목록 조회
GET http://localhost:8000/boards

###
# 게시글 상세 조회
GET http://localhost:8000/boards/6

###
# 게시글 등록
POST http://localhost:8000/boards
Content-Type: application/json

{
    "writeName": "곰돌이",
    "title": "도레미파",
    "contents": "솔라시도"
}

###
# 게시글 수정
PUT http://localhost:8000/boards/10
Content-Type: application/json

{
"writeName": "김둘리",
"title": "호이호이",
"contents": "메롱"
}

###
# 게시글 삭제
DELETE http://localhost:8000/boards/13




